"index.tsx" -> "pages/routes"
"index.tsx" -> "global"

"pages/routes": {
  "routes"
  "pages"
}

"global": {
  "config"
  "dict"
  "types"
  "utils"
}

"pages/routes" -> "global"
"pages/routes" -> "api"
"pages/routes" -> "components"
"pages/routes" -> "logic"."index.ts"
"pages/routes" -> "assets"
"pages/routes"."routes" -> "routerInstance.gen.ts"
"routerInstance.gen.ts" -> "pages/routes"."routes": {style: {stroke-dash: 3}}

"components" -> "api"
"components" -> "logic"."index.ts"
"components" -> "assets"
"components" -> "global"

"logic"."index.ts" -> "logic"."module 1"
"logic"."index.ts" -> "logic"."module 2"

"logic" -> "global"
"logic" -> "ref"

"ref": {
  "localStorage.ts"
  "globalRef.ts"
}

ref -> "global"

"api" -> "global"

# "global"."dict" {
#   "dict.ts" -> "lang"
# }
