Tech stack: {
  grid-columns: 1
  Client: {
    grid-columns: 3
    *.width: 120
    Bun: {
      icon: https://bun.sh/logo.svg
    }
    Vite: {
      icon: https://vitejs.dev/logo.svg
    }
    Mantine: {
      icon: https://mantine.dev/favicon.svg
    }
    React: {
      icon: https://react.dev/favicon.ico
    }
    Lucide: {
      icon: https://lucide.dev/logo.svg
    }
    Playwright: {
      icon: https://playwright.dev/img/playwright-logo.svg
    }
    D2lang: {
      icon: https://d2lang.com/img/favicon.ico
    }
    "Elysia/treaty": {
      icon: https://elysiajs.com/assets/elysia.png
    }
    TypeDoc: {
      icon: https://typedoc.org/assets/favicon.ico
    }
  }
  Server: {
    grid-columns: 3
    *.width: 120
    Bun: {
      icon: https://bun.sh/logo.svg
    }
    "Bun test": {
      icon: https://bun.sh/logo.svg
    }
    D2lang: {
      icon: https://d2lang.com/img/favicon.ico
    }
    Elysia: {
      icon: https://elysiajs.com/assets/elysia.png
    }
    "Elysia/swagger": {
      icon: https://elysiajs.com/assets/elysia.png
    }
    TypeDoc: {
      icon: https://typedoc.org/assets/favicon.ico
    }
  }
}
