Tech stack: {
  Client: {
    Bun
    Vite
    Preact
    Playwright
    Typedoc
    D2lang
    Mantine
    Lucide
  }
  Client -> Server: {style: {opacity: 0}}
  Server: {
    Bun
    Bun test
    Typedoc
    D2lang
    Elysia
    Elysia/swagger
  }
}
