Project structure: {
  src: {
    
    "globalState.ts"

    actions: {
      "actions.state.ts"
      "actions.types.ts"
      "actions.interface.ts"
      "actions.utils.ts"
      "actions.impl.ts"
      impl

      "actions.types.ts" -> impl
      "actions.utils.ts" -> impl
      "actions.interface.ts" -> impl
      "actions.state.ts" -> impl
      "actions.state.ts" -> "actions.impl.ts"
      impl -> "actions.impl.ts"
    }

    api
    tr

    components: {
      _app
      feature1
      feature2 {
        "Feature2.imports.ts"
        "Feature2.tsx"

        "Feature2.imports.ts" -> "Feature2.tsx"
      }

      _app -> feature1
      _app -> feature2
      feature1 -> feature2."Feature2.imports.ts"
    }

    "(readOnlyGlobalState)": {
      "gs.ts"
      Shared
      utils
      assets
    }

    "globalState.ts" -> actions."actions.state.ts"
    "globalState.ts" -> "(readOnlyGlobalState)"."gs.ts"
    actions."actions.impl.ts" -> components
    actions."actions.impl.ts" -> "(readOnlyGlobalState)"
    api -> actions
    tr -> "(readOnlyGlobalState)"."gs.ts"
    "(readOnlyGlobalState)" -> routes
    components -> routes
  }
}

A -> B: can be imported by
