Project structure: {
  src: {
    "(readWriteGlobalState)": {
      "globalState.ts"
      utils
      Shared
      "dict.ts"
    }

    api

    actions: {
      "actions.impl.ts"
      impl

      impl -> "actions.impl.ts"
    }

    components: {
      _commonFeature
      feature1
      feature2

      _commonFeature -> feature1
      _commonFeature -> feature2
    }

    routes

    "(readWriteGlobalState)" -> actions.impl
    "(readWriteGlobalState)" -> components
    "(readWriteGlobalState)" -> routes
    api -> actions.impl
    actions."actions.impl.ts" -> components
    actions."actions.impl.ts" -> routes
    components -> routes
  }
}

A -> B: can be imported by
