Server: {
  grid-columns: 3
  *.width: 120
  Bun: {
    icon: https://bun.sh/logo.svg
  }
  "Bun test": {
    icon: https://bun.sh/logo.svg
  }
  D2lang: {
    icon: https://d2lang.com/img/favicon.ico
  }
  Elysia: {
    icon: https://elysiajs.com/assets/elysia.png
  }
  "Elysia/swagger": {
    icon: https://elysiajs.com/assets/elysia.png
  }
  TypeDoc: {
    icon: https://typedoc.org/assets/favicon.ico
  }
}
